language:
    - python

python:
    - "2.7"
    - "3.5"
    - "3.6"

cache:
  pip: true
  bundler: true

notifications:
  email: false

before_install:
    - "sudo apt-get install -qq python-scipy"

# command to install dependencies
install:
    - "pip install -r requirements.txt"
    - "pip install python-coveralls"
    - "pip install coveralls"
    - "pip install nose"
    - "pip install scikit-learn"
    - "pip install 'joblib==0.11' --force-reinstall"
    - "python setup.py develop"

# command to run tests
script:
    - "nosetests --with-coverage --cover-erase --cover-package=sed_eval -v -w tests/"

after_success:
    - "coveralls"
    - "python setup.py develop --uninstall"

after_failure:
    - "python setup.py develop --uninstall"